import { chromium } from 'playwright';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1512, height: 950 }, deviceScaleFactor: 1 });
const p = await ctx.newPage();
await p.goto('http://localhost:4321/', { waitUntil: 'networkidle' });
await p.waitForTimeout(6000);
await p.evaluate(() => {
  window.__hits = [];
  window.__q = window.matchMedia(`(resolution: ${window.devicePixelRatio}dppx)`);
  window.__q.addEventListener('change', () => window.__hits.push('resolution-query fired, dpr now ' + window.devicePixelRatio));
  window.addEventListener('resize', () => window.__hits.push('window resize fired, dpr now ' + window.devicePixelRatio));
  const c = document.querySelector('[data-prop="brain"] canvas');
  new ResizeObserver(() => window.__hits.push('canvas ResizeObserver fired')).observe(c);
});
const cdp = await ctx.newCDPSession(p);
await cdp.send('Emulation.setDeviceMetricsOverride', { width: 1512, height: 950, deviceScaleFactor: 2, mobile: false });
await p.waitForTimeout(1500);
console.log('dpr now:', await p.evaluate(() => window.devicePixelRatio));
console.log('events seen:', await p.evaluate(() => window.__hits));
console.log('query matches:', await p.evaluate(() => window.__q.matches + ' (media: ' + window.__q.media + ')'));
await b.close();
