import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { gsap, ScrollTrigger, ensureGsap } from '@/lib/gsap';
import HoverLink from './HoverLink';

const SOCIALS = [
  { label: 'GitHub', href: 'https://github.com/BlazPocrnja' },
  { label: 'LinkedIn', href: 'https://www.linkedin.com/in/blaz-pocrnja' },
];

const NAV = [
  { label: 'Work', href: '/work' },
  { label: 'Info', href: '/info' },
  { label: 'Contact', href: '/contact' },
];

/*
 * THE SHADOW BOX — the hero is a screen translation of a physical laser-cut
 * lightbox: a proscenium frame holding stacked engraving layers at real
 * depths, lit from behind. Scrolling dollies the camera through the frame,
 * past the reaching hands, between the devil and the cockatrice, and into
 * the brain/glow at the very back.
 *
 * The artwork lives in /public/hero/*.png and is applied as CSS ALPHA MASKS
 * colored with theme tokens — swap any file for your own black-on-transparent
 * engraving (same filename) and it inherits both themes automatically.
 * White-background exports? Run `node scripts/prep-hero-assets.mjs`.
 * Placeholder art is generated by `node scripts/hero-placeholders.mjs`.
 */

const PERSP = 800; // px — perspective distance; shorter = wider FOV, stronger parallax
const DOLLY_START = 0.06; // fraction of scroll before the camera starts moving
const TRAVEL = 1350; // px of camera travel across the full scroll
const KILL_START = 120; // z at which a layer passing the camera starts fading
const KILL_RANGE = 360; // z distance over which that fade completes

/** Deterministic PRNG so the SSR and client renders agree on the starfield. */
function mulberry32(seed: number) {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Chevron rail matching the laser-cut border (Asset 1.png): a uniform
 * field of right triangles — square cells, hypotenuses forming one
 * continuous zigzag, alternately anchored to each side of the field — with
 * one margin before the element's own border-right, which is the strip's
 * rule. The tile height is fitted by JS so a whole number of cells fills
 * the screen. */
const RAIL = `url("data:image/svg+xml,${encodeURIComponent(
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 72"><path d="M0 0 L0 36 L36.4 36 Z" fill="#000"/><path d="M36.4 36 L36.4 72 L0 72 Z" fill="#000"/><rect x="36" y="0" width="1.4" height="72" fill="#000"/></svg>'
)}")`;

/** Hand-drawn star glyphs sliced from the user's stars.png sheet by
 * scripts/build-hero-masks.mjs — real ink shapes, not procedural stars. */
const SPARK_GLYPHS = Array.from({ length: 8 }, (_, i) => `url('/hero/spark-${i}.png')`);

interface SceneLayer {
  id: string;
  z: number; // resting depth (negative = deeper into the box)
  w: number; // PROJECTED width at p=0, % of stage width
  ar: number; // aspect ratio w/h
  x?: number; // projected offset from stage center, % of stage width
  y?: number; // projected offset from stage center, % of stage height
  rot?: number;
  op?: number;
  mask?: string; // CSS mask url — /hero/*.png slot or data-URI
  tone?: string; // fill color for masked art
  maskLight?: string; // alternate mask swapped in under the light theme
  toneLight?: string; // fill for the light-theme variant
  idle?: 'float' | 'float-b' | 'float-c' | 'hands'; // idle-animation role
  kind?: 'interior' | 'halo' | 'floor' | 'spark';
  spark?: 'star' | 'light'; // particle flavor: ink sparkle vs glowing light
  lightc?: string; // glow color family for 'light' sparks
  dur?: number; // spark twinkle duration
  delay?: number; // spark twinkle phase offset
}

const BASE_LAYERS: SceneLayer[] = [
  { id: 'interior', z: -1040, w: 99, ar: 1.58, kind: 'interior' },
  { id: 'halo', z: -905, w: 46, ar: 1, y: -10, op: 0.9, kind: 'halo' },
  { id: 'brain', z: -890, w: 26, ar: 460 / 689, y: -11, mask: "url('/hero/brain.png')", tone: 'color-mix(in srgb, var(--fg) 96%, var(--bg))', idle: 'float' },
  { id: 'clouds', z: -770, w: 96, ar: 3958 / 1005, y: -31, mask: "url('/hero/clouds.png')", tone: 'color-mix(in srgb, var(--fg) 46%, var(--bg))' },
  { id: 'floor', z: -410, w: 170, ar: 1.6, y: 34, op: 0.85, kind: 'floor' },
  /* the creatures carry a light-theme ink variant: there they render as the
     original engravings (black ink on paper) instead of tonal negatives */
  { id: 'devil', z: -250, w: 16.5, ar: 555 / 1024, x: -24, y: 8, mask: "url('/hero/devil.png')", tone: 'color-mix(in srgb, var(--fg) 74%, var(--bg))', maskLight: "url('/hero/devil-ink.png')", toneLight: 'color-mix(in srgb, var(--fg) 86%, var(--bg))', idle: 'float-b' },
  { id: 'cockatrice', z: -490, w: 19, ar: 720 / 661, x: 19, y: 11, mask: "url('/hero/cockatrice.png')", tone: 'color-mix(in srgb, var(--fg) 82%, var(--bg))', maskLight: "url('/hero/cockatrice-ink.png')", toneLight: 'color-mix(in srgb, var(--fg) 90%, var(--bg))', idle: 'float-c' },
  /* hands: one shared near-camera plane, big enough that the exports' hard
     canvas edges sit off-screen — first-person hands entering from the wings */
  { id: 'hand-left', z: -70, w: 44, ar: 375 / 500, x: -50, y: 20, rot: -6, mask: "url('/hero/hand-left.png')", tone: 'color-mix(in srgb, var(--fg) 88%, var(--bg))', idle: 'hands' },
  { id: 'hand-right', z: -70, w: 44, ar: 375 / 500, x: 50, y: 10, rot: 4, mask: "url('/hero/hand-right.png')", tone: 'color-mix(in srgb, var(--fg) 88%, var(--bg))', idle: 'hands' },
];

/* Depth-scattered particles: ink sparkles + glowing lights (some accent,
 * some uncolored — bright-white in dark theme, ink in light), spread through
 * the volume so the dolly flies past them at different rates. Rejection
 * sampling keeps them from clumping in the rest view. Seeded so SSR/client
 * agree. */
const sprng = mulberry32(21);
const SPARKS: SceneLayer[] = [];
{
  let attempts = 0;
  while (SPARKS.length < 14 && attempts < 400) {
    attempts++;
    const light = sprng() < 0.45;
    const z = -(380 + sprng() * 570);
    // lights stay small — points in the dark, not billboards
    const w = light ? 1.3 + sprng() * 1.8 : 1.1 + sprng() * 1.7;
    const x = -44 + sprng() * 88;
    const y = -26 + sprng() * 52;
    const op = 0.5 + sprng() * 0.5;
    const dur = 2.2 + sprng() * 2.6;
    const delay = -sprng() * 4;
    // big particles stick to the drawn star shapes (glyphs are sorted by
    // area, largest first); the round ink dots only ever appear tiny
    const glyph = Math.floor(sprng() * (w > 1.6 ? 4 : SPARK_GLYPHS.length));
    sprng(); // retained draw — keeps the seeded layout stable
    // min projected spacing (y is in stage-height %, so scale to width units)
    if (SPARKS.some((s) => Math.hypot(s.x! - x, (s.y! - y) * 0.625) < 10)) continue;
    // no rotation — drawn stars keep their tips pointing up, like the sheet.
    // all lights glow uncolored (bone in dark, ink in light) — the accent
    // belongs to the big ember glow alone
    SPARKS.push({
      id: `spark-${SPARKS.length}`, z, w, ar: 1, x, y, op, dur, delay,
      kind: 'spark', spark: light ? 'light' : 'star',
      mask: SPARK_GLYPHS[glyph],
      tone: 'color-mix(in srgb, var(--fg) 85%, var(--bg))',
      lightc: 'var(--fg)',
    });
  }
}

/* Far-field sky: a dust of tiny, dim stars in the band between the brain
 * (-890) and the back panel (-1040), so the box reads as opening onto night
 * sky beyond the scenery — the brain occludes some of them, which is exactly
 * what sells the depth. Smaller, dimmer, denser, and uncolored (no accent
 * this deep). */
{
  const deep: SceneLayer[] = [];
  let attempts = 0;
  while (deep.length < 16 && attempts < 500) {
    attempts++;
    const light = sprng() < 0.25;
    const z = -(900 + sprng() * 130);
    const w = 0.45 + sprng() * 0.75;
    const x = -46 + sprng() * 92;
    const y = -30 + sprng() * 58;
    const op = 0.3 + sprng() * 0.4;
    const dur = 2.8 + sprng() * 3.2;
    const delay = -sprng() * 5;
    // small end of the glyph sheet only — these are pinpricks, not features
    const glyph = 2 + Math.floor(sprng() * (SPARK_GLYPHS.length - 2));
    if (deep.some((s) => Math.hypot(s.x! - x, (s.y! - y) * 0.625) < 6)) continue;
    deep.push({
      id: `deep-star-${deep.length}`, z, w, ar: 1, x, y, op, dur, delay,
      kind: 'spark', spark: light ? 'light' : 'star',
      mask: SPARK_GLYPHS[glyph],
      tone: 'color-mix(in srgb, var(--fg) 70%, var(--bg))',
      lightc: 'var(--fg)',
    });
  }
  SPARKS.push(...deep);
}

/* Space dust: the deepest field, pressed right up against the back panel —
 * dozens of near-subpixel motes at very low opacity. Individually invisible,
 * together they read as a galaxy floor behind everything, and their slow
 * parallax against the deep stars is what makes the void feel volumetric. */
{
  const dust: SceneLayer[] = [];
  let attempts = 0;
  while (dust.length < 34 && attempts < 900) {
    attempts++;
    const light = sprng() < 0.18;
    const z = -(1000 + sprng() * 36);
    const w = 0.22 + sprng() * 0.42;
    const x = -49 + sprng() * 98;
    const y = -34 + sprng() * 66;
    const op = 0.16 + sprng() * 0.3;
    const dur = 3.4 + sprng() * 3.8;
    const delay = -sprng() * 6;
    // dots only — at this size the drawn sparkles would just smear
    const glyph = 4 + Math.floor(sprng() * (SPARK_GLYPHS.length - 4));
    if (dust.some((s) => Math.hypot(s.x! - x, (s.y! - y) * 0.625) < 3.5)) continue;
    dust.push({
      id: `dust-${dust.length}`, z, w, ar: 1, x, y, op, dur, delay,
      kind: 'spark', spark: light ? 'light' : 'star',
      mask: SPARK_GLYPHS[glyph],
      tone: 'color-mix(in srgb, var(--fg) 60%, var(--bg))',
      lightc: 'var(--fg)',
    });
  }
  SPARKS.push(...dust);
}

/* Back-to-front by depth — DOM order is paint order. */
const LAYERS: SceneLayer[] = [...BASE_LAYERS, ...SPARKS].sort((a, b) => a.z - b.z);

/** Perspective projection factor: element sizes/offsets are authored as what
 * you SEE at p=0; this converts them to the actual (larger, deeper) values. */
function proj(z: number) {
  return (PERSP - z) / PERSP;
}

function layerTransform(l: SceneLayer, z: number) {
  const base = `translate3d(-50%, -50%, ${z.toFixed(1)}px)`;
  if (l.kind === 'floor') return `${base} rotateX(78deg)`;
  return l.rot ? `${base} rotate(${l.rot}deg)` : base;
}

const CONTENT_FADE_END = 0.12; // hero tagline/name/nav are gone by this fraction

export default function Hero() {
  const taglineRef = useRef<HTMLDivElement>(null);
  const scrollWrapRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  const washRef = useRef<HTMLDivElement>(null);
  const sceneRef = useRef<HTMLDivElement>(null);
  const layerRefs = useRef<Array<HTMLDivElement | null>>([]);
  const [tallHero, setTallHero] = useState(true);

  useEffect(() => {
    if (!taglineRef.current) return;
    gsap.fromTo(
      taglineRef.current,
      { opacity: 0, y: 16 },
      { opacity: 1, y: 0, duration: 1, delay: 0.6, ease: 'power3.out' }
    );
  }, []);

  useEffect(() => {
    setTallHero(!window.matchMedia('(prefers-reduced-motion: reduce)').matches);
  }, []);

  // Fit the rail pattern: snap the repeat-tile height so a whole number of
  // triangle cells fills the rail exactly — no clipped cell at the bottom.
  useEffect(() => {
    const wrap = scrollWrapRef.current;
    if (!wrap) return;
    const rail = wrap.querySelector<HTMLElement>('.hero-rail');
    const fit = () => {
      if (!rail) return;
      const h = rail.clientHeight;
      const idealTile = rail.clientWidth * (72 / 40); // 2 square-ish cells per tile
      const n = Math.max(1, Math.round(h / idealTile));
      wrap.style.setProperty('--rail-tile', `${(h / n).toFixed(2)}px`);
    };
    fit();
    window.addEventListener('resize', fit);
    return () => window.removeEventListener('resize', fit);
  }, []);

  // Tracks whether any part of the hero (including mid-flythrough, not just
  // the very top) is on screen, persisted so Layout.astro's preloader-skip
  // script can read it on the NEXT load: refreshing while still within the
  // hero replays the intro (Preloader.tsx resets scroll to top while hidden
  // behind its curtain), but refreshing after scrolling into the regular
  // page content skips it and leaves scroll position alone.
  useEffect(() => {
    const wrap = scrollWrapRef.current;
    if (!wrap) return;
    const io = new IntersectionObserver(
      ([entry]) => {
        try {
          sessionStorage.setItem('hero-in-view', entry.isIntersecting ? '1' : '0');
        } catch {
          // sessionStorage can throw in private-browsing/sandboxed contexts — the
          // preloader just falls back to always showing on reload in that case.
        }
      },
      { threshold: 0 }
    );
    io.observe(wrap);
    return () => io.disconnect();
  }, []);

  useEffect(() => {
    if (!tallHero) return;
    ensureGsap();
    const wrap = scrollWrapRef.current;
    const content = contentRef.current;
    if (!wrap || !content) return;

    const layers = layerRefs.current.filter((el): el is HTMLDivElement => el !== null);

    const wash = washRef.current;

    const update = (p: number) => {
      // exponent > 1 makes the camera accelerate through the scroll — the
      // "pulled into the light" feeling of an opening cinematic
      const pl = Math.max(0, (p - DOLLY_START) / (1 - DOLLY_START));
      const pe = Math.pow(pl, 1.55);
      const dz = pe * TRAVEL;

      layers.forEach((el, i) => {
        const l = LAYERS[i];
        const zNow = Math.min(l.z + dz, PERSP - 60);
        let op = l.op ?? 1;
        if (zNow > KILL_START) op *= Math.max(0, 1 - (zNow - KILL_START) / KILL_RANGE);
        el.style.transform = layerTransform(l, zNow);
        el.style.opacity = op.toFixed(3);
      });

      const fadeP = Math.min(1, p / CONTENT_FADE_END);
      content.style.opacity = (1 - fadeP).toFixed(3);
      content.style.filter = fadeP > 0 ? `blur(${(fadeP * 6).toFixed(1)}px)` : 'none';

      // Finale: the light swallows the screen over the last stretch, so the
      // sticky release hands the next section a bright frame to rise over.
      if (wash) {
        const wp = Math.min(1, Math.max(0, (p - 0.84) / 0.14));
        const eased = wp * wp * (3 - 2 * wp);
        wash.style.opacity = eased.toFixed(3);
      }
    };

    // Dev-only tuning hook: /?heroP=0.5 freezes the dolly at that progress.
    if (import.meta.env.DEV) {
      const raw = new URLSearchParams(window.location.search).get('heroP');
      const dbg = raw === null ? NaN : Number(raw);
      if (!Number.isNaN(dbg) && dbg >= 0) {
        update(Math.min(1, dbg));
        return;
      }
    }

    const trigger = ScrollTrigger.create({
      trigger: wrap,
      start: 'top top',
      end: 'bottom bottom',
      scrub: true,
      onUpdate: (self) => update(self.progress),
    });

    // Prop-setup entrance: on a fresh intro (not a skip-reload), the scene
    // assembles like stagehands placing a set — frame and light first, then
    // scenery lowered in, actors dropped onto the boards with a small
    // overshoot, hands reaching in last. `immediateRender: true` parks every
    // prop in its hidden "from" state at hydration, while the preloader
    // curtain still covers the stage; the timeline starts as the curtain
    // lifts. Animates .hl-prop wrappers only — the dolly owns .hl.
    let entrance: gsap.core.Timeline | undefined;
    const freshIntro = document.documentElement.getAttribute('data-intro') !== 'skip';
    if (freshIntro && sceneRef.current) {
      const q = gsap.utils.selector(wrap);
      const prop = (id: string) => q(`[data-prop="${id}"]`);
      const ir = { immediateRender: true } as const;
      entrance = gsap.timeline({ delay: 2.3, defaults: { ease: 'power3.out' } });
      entrance
        .from(q('.hero-rail'), { opacity: 0, duration: 0.7, ...ir }, 0)
        .from(prop('interior'), { opacity: 0, duration: 1.0, ...ir }, 0.1)
        .from(prop('floor'), { opacity: 0, yPercent: 18, duration: 0.9, ...ir }, 0.35)
        .from(prop('clouds'), { yPercent: -180, duration: 1.0, ...ir }, 0.5)
        .from(prop('halo'), { opacity: 0, duration: 1.0, ...ir }, 0.8)
        .from(prop('brain'), { yPercent: 55, opacity: 0, duration: 1.0, ease: 'power2.out', ...ir }, 0.8)
        .from(prop('devil'), { yPercent: -140, duration: 0.75, ease: 'back.out(1.3)', ...ir }, 1.15)
        .from(prop('cockatrice'), { yPercent: -140, duration: 0.75, ease: 'back.out(1.3)', ...ir }, 1.35)
        .from(prop('hand-left'), { xPercent: -75, opacity: 0, duration: 0.9, ...ir }, 1.55)
        .from(prop('hand-right'), { xPercent: 75, opacity: 0, duration: 0.9, ...ir }, 1.7)
        .from(q('[data-spark]'), { opacity: 0, scale: 0.5, duration: 0.7, stagger: 0.045, ...ir }, 0.75);
    }

    // Head-tracking parallax: easing the perspective-origin toward the
    // pointer shifts every layer proportionally to its depth — the cheap,
    // honest way to make the box read as a real space you're peering into.
    const scene = sceneRef.current;
    const look = { x: 0, y: 0 };
    const lookTarget = { x: 0, y: 0 };
    const canHover = window.matchMedia('(hover: hover)').matches;
    const onPointerMove = (e: PointerEvent) => {
      lookTarget.x = (e.clientX / window.innerWidth - 0.5) * 7;
      lookTarget.y = (e.clientY / window.innerHeight - 0.5) * 5;
    };
    const lookTick = () => {
      look.x += (lookTarget.x - look.x) * 0.05;
      look.y += (lookTarget.y - look.y) * 0.05;
      if (scene) scene.style.perspectiveOrigin = `${(50 + look.x).toFixed(3)}% ${(50 + look.y).toFixed(3)}%`;
    };
    if (canHover && scene) {
      window.addEventListener('pointermove', onPointerMove);
      gsap.ticker.add(lookTick);
    }

    return () => {
      trigger.kill();
      entrance?.kill();
      if (canHover && scene) {
        window.removeEventListener('pointermove', onPointerMove);
        gsap.ticker.remove(lookTick);
      }
    };
  }, [tallHero]);

  return (
    <div ref={scrollWrapRef} className={`hero-scroll-wrap${tallHero ? '' : ' is-compact'}`}>
      <section className="hero">
        <div className="hero-canvas" aria-hidden="true">
          <div ref={sceneRef} className="hero-scene">
            {LAYERS.map((l, i) => {
              const f = proj(l.z);
              return (
                <div
                  key={l.id}
                  ref={(el) => {
                    layerRefs.current[i] = el;
                  }}
                  className="hl"
                  style={{
                    width: `calc(var(--stageW) * ${((l.w * f) / 100).toFixed(4)})`,
                    aspectRatio: `${l.ar}`,
                    left: `calc(50% + var(--stageW) * ${(((l.x ?? 0) * f) / 100).toFixed(4)})`,
                    top: `calc(50% + var(--stageH) * ${(((l.y ?? 0) * f) / 100).toFixed(4)})`,
                    transform: layerTransform(l, l.z),
                    opacity: l.op ?? 1,
                  }}
                >
                  <div className="hl-prop" data-prop={l.id} data-spark={l.kind === 'spark' ? '' : undefined}>
                    {l.kind === 'spark' &&
                      (l.spark === 'star' ? (
                        <div
                          className="hl-ink hl-spark"
                          style={{
                            backgroundColor: l.tone,
                            WebkitMaskImage: l.mask,
                            maskImage: l.mask,
                            animationDuration: `${l.dur}s`,
                            animationDelay: `${l.delay}s`,
                          }}
                        />
                      ) : (
                        <div
                          className="hl-light"
                          style={{
                            animationDuration: `${l.dur}s`,
                            animationDelay: `${l.delay}s`,
                            ...({ '--lightc': l.lightc } as CSSProperties),
                          }}
                        />
                      ))}
                    {l.kind === 'interior' && (
                      <div className="hl-interior">
                        <div className="hl-glow" />
                      </div>
                    )}
                    {l.kind === 'halo' && <div className="hl-halo" />}
                    {l.kind === 'floor' && <div className="hl-floor" />}
                    {l.mask && l.kind !== 'spark' && (
                      <div className={`hl-art${l.idle ? ` idle-${l.idle}` : ''}`}>
                        <div
                          className={`hl-ink${l.maskLight ? ' theme-dark-only' : ''}`}
                          style={{ backgroundColor: l.tone, WebkitMaskImage: l.mask, maskImage: l.mask }}
                        />
                        {l.maskLight && (
                          <div
                            className="hl-ink theme-light-only"
                            style={{ backgroundColor: l.toneLight, WebkitMaskImage: l.maskLight, maskImage: l.maskLight }}
                          />
                        )}
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          {/* The screen IS the proscenium: dogtooth rails pinned to the
              viewport edges, outside the dolly — they never fly past. */}
          <div className="hero-rail is-left" />
          <div className="hero-rail is-right" />
        </div>

        <div ref={washRef} className="hero-wash" aria-hidden="true" />

        <div ref={contentRef} className="hero-content">
          <div ref={taglineRef} className="hero-tagline">
            Quiet creator, <span className="other-accent">bringing ideas to life</span>,
            <br />
            through motion, detail and softness.
          </div>

          <div className="hero-bottom">
            <h1 className="hero-name">Blaz Pocrnja.</h1>
            <div className="hero-line" />
            <div className="hero-bar">
              <div className="hero-bar-left">
                <HoverLink label="v1.0" />
              </div>
              <nav className="hero-bar-center" aria-label="Social links">
                {SOCIALS.map((s, i) => (
                  <span key={s.label} style={{ display: 'flex', gap: '0.5em' }}>
                    <a href={s.href} target="_blank" rel="noopener noreferrer">
                      <HoverLink label={s.label} />
                    </a>
                    {i < SOCIALS.length - 1 && <span className="sep">/</span>}
                  </span>
                ))}
              </nav>
              <nav className="hero-bar-right" aria-label="Main navigation">
                {NAV.map((n) => (
                  <a key={n.label} href={n.href}>
                    <HoverLink label={n.label} />
                  </a>
                ))}
              </nav>
            </div>
          </div>
        </div>
      </section>

      {/* dangerouslySetInnerHTML avoids a React SSR/hydration text-escaping mismatch for raw-text elements like <style> (this one trips it via the `>` in `.hero-content > *`) */}
      <style dangerouslySetInnerHTML={{ __html: `
        .hero-scroll-wrap {
          position: relative;
          height: 400vh;
        }
        .hero-scroll-wrap.is-compact {
          height: 100vh;
        }
        .hero {
          position: sticky;
          top: 0;
          height: 100vh;
          min-height: 560px;
          overflow: hidden;
        }
        .hero-scroll-wrap.is-compact .hero {
          position: relative;
        }
        .hero-canvas {
          position: absolute;
          inset: 0;
          z-index: 0;
          background: var(--bg);
        }
        .hero-scene {
          position: absolute;
          inset: 0;
          perspective: ${PERSP}px;
          --stageW: min(94vw, 140vh);
          --stageH: calc(var(--stageW) / 1.6);
        }
        @media (max-width: 640px) {
          .hero-scene {
            --stageW: min(96vw, 120vh);
          }
        }
        .hl {
          position: absolute;
          will-change: transform, opacity;
          pointer-events: none;
        }
        /* Three transform tiers that never fight: .hl belongs to the scroll
           dolly (JS), .hl-prop to the one-shot prop-setup entrance (GSAP),
           .hl-art to the CSS idle loops. */
        .hl-prop {
          position: absolute;
          inset: 0;
        }
        .hl-art,
        .hl-ink,
        .hl-light,
        .hl-interior,
        .hl-halo,
        .hl-floor,
        .hl-frame {
          position: absolute;
          inset: 0;
        }
        .hl-ink {
          -webkit-mask-size: 100% 100%;
          mask-size: 100% 100%;
          -webkit-mask-repeat: no-repeat;
          mask-repeat: no-repeat;
        }
        .theme-light-only {
          display: none;
        }
        :root[data-theme='light'] .theme-light-only {
          display: block;
        }
        :root[data-theme='light'] .theme-dark-only {
          display: none;
        }
        .hl-spark {
          animation: hl-spark 3s ease-in-out infinite alternate;
        }
        /* Distant lanterns: hot core, colored ring, wide soft falloff,
           composited additively so overlaps bloom like real lights. The
           color family comes from --lightc per particle: accent lanterns or
           uncolored ones (bright bone in the dark theme, ink in light). */
        .hl-light {
          --lightc: var(--accent);
          background: radial-gradient(circle,
            color-mix(in srgb, var(--lightc) 30%, var(--fg)) 0%,
            var(--lightc) 11%,
            color-mix(in srgb, var(--lightc) 55%, transparent) 28%,
            color-mix(in srgb, var(--lightc) 20%, transparent) 48%,
            transparent 72%);
          mix-blend-mode: screen;
          animation: hl-spark 3s ease-in-out infinite alternate;
        }
        :root[data-theme='light'] .hl-light {
          mix-blend-mode: multiply;
        }
        @keyframes hl-spark {
          from { opacity: 0.4; transform: scale(0.88); }
          to { opacity: 1; transform: scale(1.1); }
        }
        /* The light source behind the scenery — glow only, no panel fill:
           a visible rectangle edge against the void reads as a seam. */
        .hl-interior {
          background: transparent;
        }
        .hl-glow {
          position: absolute;
          inset: 0;
          border-radius: inherit;
          background: radial-gradient(ellipse 62% 58% at 50% 40%, color-mix(in srgb, var(--accent) 34%, transparent), transparent 72%);
          animation: hl-flicker 5.2s ease-in-out infinite;
        }
        .hl-halo {
          background: radial-gradient(circle, color-mix(in srgb, var(--accent) 42%, transparent), transparent 68%);
          animation: hl-flicker 4.1s ease-in-out -1.7s infinite;
        }
        .hl-floor {
          background: repeating-conic-gradient(color-mix(in srgb, var(--fg) 30%, transparent) 0% 25%, transparent 0% 50%);
          background-size: clamp(64px, 8.5vw, 118px) clamp(64px, 8.5vw, 118px);
          -webkit-mask-image: radial-gradient(closest-side, #000 45%, transparent 92%);
          mask-image: radial-gradient(closest-side, #000 45%, transparent 92%);
        }
        /* Screen-edge proscenium rails: full viewport height, alternating
           right triangles like the laser-cut border of the physical box.
           The strip itself is SOLID (page-colored) — the scene never shows
           through it; the triangles paint on top via the mask. */
        .hero-rail {
          position: absolute;
          top: 0;
          bottom: 0;
          width: clamp(44px, 5.2vw, 92px);
          background: var(--bg);
          /* the strip's rule — flips to the correct side on the mirrored
             right rail along with the rest of the element */
          border-right: 2px solid color-mix(in srgb, var(--fg) 40%, var(--bg));
        }
        .hero-rail::before {
          content: '';
          position: absolute;
          inset: 0;
          background: color-mix(in srgb, var(--fg) 40%, var(--bg));
          -webkit-mask-image: ${RAIL};
          mask-image: ${RAIL};
          -webkit-mask-size: 100% var(--rail-tile, auto);
          mask-size: 100% var(--rail-tile, auto);
          -webkit-mask-repeat: repeat-y;
          mask-repeat: repeat-y;
        }
        .hero-rail.is-left {
          left: 0;
        }
        .hero-rail.is-right {
          right: 0;
          transform: scaleX(-1);
        }
        /* Idle life: candle-flicker on the light, game-style idle loops on
           the cast. These animate INNER elements only — the outer .hl
           transforms belong to the scroll dolly, so the two never fight. */
        @keyframes hl-flicker {
          0%, 100% { opacity: 1; }
          31% { opacity: 0.82; }
          47% { opacity: 0.95; }
          62% { opacity: 0.78; }
          81% { opacity: 0.92; }
        }
        /* everything hangs weightless: the same gentle bob at staggered
           periods — puppets suspended in the box */
        @keyframes hl-idle-float {
          from { transform: translateY(1.4%) rotate(-0.7deg); }
          to { transform: translateY(-2%) rotate(0.6deg); }
        }
        .idle-float { animation: hl-idle-float 5.6s ease-in-out infinite alternate; }
        .idle-float-b { animation: hl-idle-float 6.8s ease-in-out -2.4s infinite alternate; }
        .idle-float-c { animation: hl-idle-float 7.6s ease-in-out -4.6s infinite alternate; }
        /* the hands share ONE plane and ONE rhythm — first-person-camera
           hands, swaying together, so identical timing and no phase offset */
        @keyframes hl-idle-hands {
          from { transform: translate(0.5%, 1%) rotate(0.25deg); }
          to { transform: translate(-0.5%, -1.4%) rotate(-0.25deg); }
        }
        .idle-hands { animation: hl-idle-hands 5s ease-in-out infinite alternate; }
        /* Finale wash: dark theme fades to black with a dying ember at the
           center (a white flash out of the void was jarring); light theme
           blooms to white — the literal lamp, not a surface token. */
        .hero-wash {
          position: absolute;
          inset: 0;
          z-index: 2;
          pointer-events: none;
          opacity: 0;
          background: radial-gradient(circle at 50% 44%,
            color-mix(in srgb, var(--accent) 22%, #000),
            color-mix(in srgb, var(--accent) 8%, #000) 50%,
            #000 100%);
          will-change: opacity;
        }
        :root[data-theme='light'] .hero-wash {
          background: radial-gradient(circle at 50% 44%,
            color-mix(in srgb, var(--accent) 42%, #fff),
            color-mix(in srgb, var(--accent) 18%, #fff) 55%,
            #fff 100%);
        }
        .hero-content {
          position: absolute;
          inset: 0;
          z-index: 1;
          pointer-events: none;
          will-change: opacity, filter;
        }
        .hero-content > * {
          pointer-events: auto;
        }
        .hero-tagline {
          position: absolute;
          top: var(--container-pad);
          left: var(--container-pad);
          font-family: var(--font-serif);
          font-size: clamp(1.6rem, 3.2vw, 2.6rem);
          font-weight: 400;
          line-height: 1.3;
          max-width: 14ch;
        }
        .hero-bottom {
          position: absolute;
          left: var(--container-pad);
          right: var(--container-pad);
          bottom: var(--container-pad);
        }
        .hero-name {
          font-family: var(--font-display);
          font-size: clamp(2.5rem, 9vw, 6.5rem);
          font-weight: 900;
          letter-spacing: 0;
          line-height: 0.9;
          margin-bottom: clamp(1.5rem, 4vw, 3rem);
        }
        .hero-line {
          height: 1px;
          background: var(--line);
          margin-bottom: 1rem;
        }
        .hero-bar {
          display: flex;
          align-items: center;
          justify-content: space-between;
          font-family: var(--font-mono);
          font-size: 0.8rem;
          text-transform: uppercase;
          letter-spacing: 0.03em;
          flex-wrap: wrap;
          gap: 0.75rem;
        }
        /* the near-camera hands pass right behind these labels — each group
           carries a translucent page-colored chip so the type stays legible
           over the dither without walling off the scene */
        .hero-bar-left,
        .hero-bar-center,
        .hero-bar-right {
          background: color-mix(in srgb, var(--bg) 72%, transparent);
          padding: 0.3em 0.55em;
          margin: -0.3em -0.55em;
          border-radius: 4px;
        }
        .hero-bar-center {
          display: flex;
          gap: 0.5em;
        }
        .hero-bar-right {
          display: flex;
          gap: 1.5em;
        }
        .sep {
          color: var(--fg-dim);
        }
        @media (max-width: 640px) {
          .hero-tagline {
            max-width: calc(100% - 2 * var(--container-pad) - 5.5rem);
          }
        }
        @media (prefers-reduced-motion: reduce) {
          .hl-glow,
          .hl-halo,
          .hl-spark,
          .hl-light,
          .idle-float,
          .idle-float-b,
          .idle-float-c,
          .idle-hands {
            animation: none;
          }
        }
      ` }} />
    </div>
  );
}
