import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { gsap, ScrollTrigger, ensureGsap } from '@/lib/gsap';
import HoverLink from './HoverLink';
import HeroAsciiArt from './HeroAsciiArt';

const SOCIALS = [
  { label: 'GitHub', href: 'https://github.com/BlazPocrnja' },
  { label: 'LinkedIn', href: 'https://www.linkedin.com/in/blaz-pocrnja' },
];

const NAV = [
  { label: 'Work', href: '/work' },
  { label: 'Info', href: '/info' },
  { label: 'Contact', href: '/contact' },
];

/*
 * THE SHADOW BOX — the hero is a screen translation of a physical laser-cut
 * lightbox: a proscenium frame holding stacked engraving layers at real
 * depths, lit from behind. Scrolling dollies the camera through the frame,
 * past the reaching hands, between the devil and the cockatrice, and into
 * the brain/glow at the very back.
 *
 * The artwork lives in /public/hero/*.png and is applied as CSS ALPHA MASKS
 * colored with theme tokens — swap any file for your own black-on-transparent
 * engraving (same filename) and it inherits both themes automatically.
 * White-background exports? Run `node scripts/prep-hero-assets.mjs`.
 * Placeholder art is generated by `node scripts/hero-placeholders.mjs`.
 */

const PERSP = 800; // px — perspective distance; shorter = wider FOV, stronger parallax
const DOLLY_START = 0.06; // fraction of scroll before the camera starts moving
const TRAVEL = 1350; // px of camera travel across the full scroll
const KILL_START = 120; // z at which a layer passing the camera starts fading
const KILL_RANGE = 360; // z distance over which that fade completes

/** Deterministic PRNG so the SSR and client renders agree on the starfield. */
function mulberry32(seed: number) {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Chevron rail matching the laser-cut border: a uniform
 * field of right triangles — square cells, hypotenuses forming one
 * continuous zigzag, alternately anchored to each side of the field — with
 * one margin before the element's own border-right, which is the strip's
 * rule. The tile height is fitted by JS so a whole number of cells fills
 * the screen. */
const RAIL = `url("data:image/svg+xml,${encodeURIComponent(
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 72"><path d="M0 0 L0 36 L36.4 36 Z" fill="#000"/><path d="M36.4 36 L36.4 72 L0 72 Z" fill="#000"/><rect x="36" y="0" width="1.4" height="72" fill="#000"/></svg>'
)}")`;

/* ---- sky glyphs -------------------------------------------------------
 *
 * The star field is plotted on a pixel grid, not drawn. It used to be ink
 * sparkles sliced off a scanned sheet, which read as hand-drawn stars in a
 * scene whose figures are now screened into x/+ stitches — the sky was the
 * one organic thing left in it. These marks come off the SAME alphabet as
 * the stitch screen (lib/halftone.ts), so the night sky and the creatures
 * are made of the same vocabulary at two different scales.
 *
 * Unit squares on an NxN viewBox, sized so each mark fills its own box: a
 * 1x1 point stays a hard pixel at dust scale, where a 5x5 asterisk shrunk
 * to the same width would just smear into a grey smudge.
 */
function pixelGlyph(size: number, cells: readonly (readonly [number, number])[]): string {
  const rects = cells.map(([x, y]) => `<rect x="${x}" y="${y}" width="1" height="1"/>`).join('');
  return `url("data:image/svg+xml,${encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" shape-rendering="crispEdges">${rects}</svg>`
  )}")`;
}

/** Diagonals of an NxN grid — the x. */
function xCells(size: number) {
  const out: [number, number][] = [];
  for (let i = 0; i < size; i++) {
    out.push([i, i]);
    out.push([i, size - 1 - i]);
  }
  return out;
}

/** Centre row + centre column — the +. */
function plusCells(size: number) {
  const c = (size - 1) / 2;
  const out: [number, number][] = [];
  for (let i = 0; i < size; i++) {
    out.push([c, i]);
    out.push([i, c]);
  }
  return out;
}

/* Ordered LARGEST/most-featured first — the scatter below slices this array
 * by depth (near particles take the feature marks, dust takes the tail), so
 * the ordering is load-bearing, not cosmetic. */
const SPARK_GLYPHS = [
  pixelGlyph(5, [...xCells(5), ...plusCells(5)]), // asterisk
  pixelGlyph(5, xCells(5)), // x
  pixelGlyph(5, plusCells(5)), // +
  pixelGlyph(3, [[0, 0], [1, 0], [2, 0], [0, 1], [2, 1], [0, 2], [1, 2], [2, 2]]), // hollow square — a registration mark
  pixelGlyph(3, xCells(3)), // small x
  pixelGlyph(3, plusCells(3)), // small +
  pixelGlyph(2, [[0, 0], [1, 0], [0, 1], [1, 1]]), // solid square
  pixelGlyph(1, [[0, 0]]), // single pixel
];

interface SceneLayer {
  id: string;
  z: number; // resting depth (negative = deeper into the box)
  w: number; // PROJECTED width at p=0, % of stage width
  ar: number; // aspect ratio w/h
  x?: number; // projected offset from stage center, % of stage width
  y?: number; // projected offset from stage center, % of stage height
  rot?: number;
  op?: number;
  mask?: string; // CSS mask url — /hero/*.png slot or data-URI
  tone?: string; // fill color for masked art
  ascii?: string; // built /hero/*.png mask, rendered as a hoverable ascii mosaic instead of a CSS mask
  asciiLight?: string; // alternate `ascii` source swapped in under the light theme
  ink?: number; // per-layer screen ink strength (see HeroAsciiArt's `ink`)
  render?: 'ascii' | 'lines' | 'dots' | 'cross' | 'dither'; // which renderer draws `ascii` — symbol mosaic (default), engraving line screen, halftone dot screen, stitched glyph screen, or the art as-authored with a hover glitch
  maskLight?: string; // alternate mask swapped in under the light theme
  toneLight?: string; // fill for the light-theme variant
  idle?: 'float' | 'float-b' | 'float-c' | 'hands'; // idle-animation role
  kind?: 'interior' | 'halo' | 'floor' | 'spark';
  spark?: 'star' | 'light'; // particle flavor: ink sparkle vs glowing light
  lightc?: string; // glow color family for 'light' sparks
  dur?: number; // spark twinkle duration
  delay?: number; // spark twinkle phase offset
  flick?: number; // which twinkle rhythm (0-2) — see the hl-twinkle keyframes
  band?: number; // which SPARK_BANDS field this star re-rolls within
}

const BASE_LAYERS: SceneLayer[] = [
  { id: 'interior', z: -1040, w: 99, ar: 1.58, kind: 'interior' },
  { id: 'halo', z: -905, w: 46, ar: 1, y: -10, op: 0.9, kind: 'halo' },
  /* The hand-dithered engraving, at the geometry it was authored for — `ar`
     is the file's own 460x689 and MUST track it or the stipple shears, which
     on a 1-bit dot pattern shows up instantly as moire. Drawn as itself
     rather than re-screened: the Photoshop dither already carries the
     texture, and its contrast beats anything derived from a photo. */
  { id: 'brain', z: -890, w: 26, ar: 460 / 689, y: -11, ascii: '/hero/brain.png', render: 'cross', idle: 'float' },
  /* far mountains: the twin-peak/valley motif from beside the candles, used
     whole as one formation directly behind the brain. Width matches the
     frieze (w:96, x:0) so both share the same left/right edges — reads as
     one continuous painted backdrop panel, diorama-style, rather than two
     independently-floating pieces. Sits at the deepest depth in the box
     (right against the interior); the floor's now-opaque checker tiles
     (see .hl-floor) hide whatever part of it would fall below the horizon. */
  /* `ink` does the recessing the old flat `tone: fg 22%` used to. A screen
     inks at its own strength, and at full strength a 96%-wide panel at the
     back of the box stops being a distant range and becomes a lit wall
     behind the whole scene. */
  { id: 'mountains', z: -980, w: 96, ar: 620 / 345, x: 0, y: 5, ascii: '/hero/mountains.png', render: 'cross', ink: 0.24 },
  /* Inks near full: the frieze is hairline cloud linework, and a screen
     that averages hairlines into 6px cells lands them mid-ramp — at the
     shared strength the whole band greyed out and stopped holding the top
     of the scene. */
  { id: 'clouds', z: -770, w: 96, ar: 3958 / 1005, y: -31, ascii: '/hero/clouds-ink.png', render: 'cross', ink: 0.95 },
  { id: 'floor', z: -410, w: 170, ar: 1.6, y: 34, kind: 'floor' },
  /* the creatures are screened rather than flat-masked — the same printed
     treatment as the hands used to wear: the engraving line screen, so the
     two figures read as hatched prints rather than solid silhouettes.
     Each carries a light-theme ink variant: there they render as the
     original engravings (black ink on paper) instead of tonal negatives */
  { id: 'devil', z: -250, w: 16.5, ar: 555 / 1024, x: -24, y: 8, ascii: '/hero/devil.png', asciiLight: '/hero/devil-ink.png', render: 'lines', idle: 'float-b' },
  { id: 'cockatrice', z: -490, w: 19, ar: 720 / 661, x: 19, y: 11, ascii: '/hero/cockatrice.png', asciiLight: '/hero/cockatrice-ink.png', render: 'lines', idle: 'float-c' },
  /* hands: one shared near-camera plane — first-person hands entering from
     the wings, at the framing the dithered exports were authored for. `ar`
     is the files' own 375x500 and MUST track it; the earlier photo cutouts
     cropped to the subject, which is why they came out both differently
     shaped and much larger on screen. The box is sized so the exports' hard
     canvas edges sit off-stage, with only the fingers and palm reaching in.
     `ink` carries the weight the old flat `tone: fg 88%` used to. */
  { id: 'hand-left', z: -70, w: 44, ar: 375 / 500, x: -50, y: 20, rot: -6, ascii: '/hero/hand-left.png', render: 'cross', ink: 0.85, idle: 'hands' },
  { id: 'hand-right', z: -70, w: 44, ar: 375 / 500, x: 50, y: 10, rot: 4, ascii: '/hero/hand-right.png', render: 'cross', ink: 0.85, idle: 'hands' },
];

/* Depth-scattered particles: ink sparkles + glowing lights (some accent,
 * some uncolored — bright-white in dark theme, ink in light), spread through
 * the volume so the dolly flies past them at different rates. Rejection
 * sampling keeps them from clumping in the rest view. Seeded so SSR/client
 * agree. */
/* The x/y range each scatter draws from, kept out here because a star has to
 * be able to re-roll INSIDE its own field for the lifetime of the page — a
 * dust mote that wandered into the near field would parallax wrongly. */
const SPARK_BANDS = [
  { x0: -44, xs: 88, y0: -26, ys: 52 }, // near sparks
  { x0: -46, xs: 92, y0: -30, ys: 58 }, // deep stars
  { x0: -49, xs: 98, y0: -34, ys: 66 }, // dust
];

const sprng = mulberry32(21);
const SPARKS: SceneLayer[] = [];
{
  let attempts = 0;
  while (SPARKS.length < 14 && attempts < 400) {
    attempts++;
    const light = sprng() < 0.45;
    const z = -(380 + sprng() * 570);
    // Roughly half the old widths. The scanned sparkles carried 8px of
    // transparent margin inside their own box, so a `w` of 3 drew a much
    // smaller star than it claimed; these marks run edge to edge, and left
    // at the old numbers they render as billboards rather than as points in
    // the dark.
    const w = light ? 0.7 + sprng() * 0.85 : 0.6 + sprng() * 0.8;
    const x = -44 + sprng() * 88;
    const y = -26 + sprng() * 52;
    const op = 0.5 + sprng() * 0.5;
    const dur = 2.2 + sprng() * 2.6;
    const delay = -sprng() * 4;
    // A LIT particle is restricted to the three feature marks. A glowing
    // solid square reads as a rendering artifact — a blown-out white box —
    // where a glowing asterisk still reads as a star.
    const gr = sprng();
    const glyph = light ? Math.floor(gr * 3) : Math.floor(gr * SPARK_GLYPHS.length);
    sprng(); // retained draw — keeps the seeded layout stable
    // min projected spacing (y is in stage-height %, so scale to width units)
    if (SPARKS.some((s) => Math.hypot(s.x! - x, (s.y! - y) * 0.625) < 10)) continue;
    // no rotation — the marks are axis-aligned by construction, and turning
    // one off its grid is what would make it read as a drawn star again.
    // all lights glow uncolored (bone in dark, ink in light) — the accent
    // belongs to the big ember glow alone
    SPARKS.push({
      id: `spark-${SPARKS.length}`, z, w, ar: 1, x, y, op, dur, delay,
      // rhythm from the INDEX, not the rng: the three fields each start on a
      // different one, so no two neighbouring particles blink in lockstep and
      // the seeded layout stays byte-identical.
      flick: SPARKS.length % 3,
      band: 0,
      kind: 'spark', spark: light ? 'light' : 'star',
      mask: SPARK_GLYPHS[glyph],
      tone: 'color-mix(in srgb, var(--fg) 85%, var(--bg))',
      lightc: 'var(--fg)',
    });
  }
}

/* Far-field sky: a dust of tiny, dim stars in the band between the brain
 * (-890) and the back panel (-1040), so the box reads as opening onto night
 * sky beyond the scenery — the brain occludes some of them, which is exactly
 * what sells the depth. Smaller, dimmer, denser, and uncolored (no accent
 * this deep). */
{
  const deep: SceneLayer[] = [];
  let attempts = 0;
  while (deep.length < 16 && attempts < 500) {
    attempts++;
    const light = sprng() < 0.25;
    const z = -(900 + sprng() * 130);
    const w = 0.3 + sprng() * 0.5;
    const x = -46 + sprng() * 92;
    const y = -30 + sprng() * 58;
    const op = 0.3 + sprng() * 0.4;
    const dur = 2.8 + sprng() * 3.2;
    const delay = -sprng() * 5;
    // small end of the alphabet only — these are pinpricks, not features,
    // and the lit ones keep clear of the solid squares for the same reason
    // the near field does
    const dr = sprng();
    const glyph = 3 + Math.floor(dr * (light ? 3 : SPARK_GLYPHS.length - 3));
    if (deep.some((s) => Math.hypot(s.x! - x, (s.y! - y) * 0.625) < 6)) continue;
    deep.push({
      id: `deep-star-${deep.length}`, z, w, ar: 1, x, y, op, dur, delay,
      flick: (deep.length + 1) % 3,
      band: 1,
      kind: 'spark', spark: light ? 'light' : 'star',
      mask: SPARK_GLYPHS[glyph],
      tone: 'color-mix(in srgb, var(--fg) 70%, var(--bg))',
      lightc: 'var(--fg)',
    });
  }
  SPARKS.push(...deep);
}

/* Space dust: the deepest field, pressed right up against the back panel —
 * dozens of near-subpixel motes at very low opacity. Individually invisible,
 * together they read as a galaxy floor behind everything, and their slow
 * parallax against the deep stars is what makes the void feel volumetric. */
{
  const dust: SceneLayer[] = [];
  let attempts = 0;
  while (dust.length < 34 && attempts < 900) {
    attempts++;
    const light = sprng() < 0.18;
    const z = -(1000 + sprng() * 36);
    const w = 0.16 + sprng() * 0.28;
    const x = -49 + sprng() * 98;
    const y = -34 + sprng() * 66;
    const op = 0.16 + sprng() * 0.3;
    const dur = 3.4 + sprng() * 3.8;
    const delay = -sprng() * 6;
    // dots only — at this size an x or a + has no room to resolve its arms
    // and collapses into a grey smudge, so these take the two square marks
    const glyph = 6 + Math.floor(sprng() * (SPARK_GLYPHS.length - 6));
    if (dust.some((s) => Math.hypot(s.x! - x, (s.y! - y) * 0.625) < 3.5)) continue;
    dust.push({
      id: `dust-${dust.length}`, z, w, ar: 1, x, y, op, dur, delay,
      flick: (dust.length + 2) % 3,
      band: 2,
      kind: 'spark', spark: light ? 'light' : 'star',
      mask: SPARK_GLYPHS[glyph],
      tone: 'color-mix(in srgb, var(--fg) 60%, var(--bg))',
      lightc: 'var(--fg)',
    });
  }
  SPARKS.push(...dust);
}

/* Back-to-front by depth — DOM order is paint order. */
const LAYERS: SceneLayer[] = [...BASE_LAYERS, ...SPARKS].sort((a, b) => a.z - b.z);

/* Churn falls off with depth. The near plane boils the way the ascii mosaic
 * does; the back of the box only drifts. Depth is normalised across the
 * range the scene actually occupies (the hands at -70 to the interior at
 * -1040) rather than against PERSP, so the gradient spends its whole range
 * on layers that exist instead of on empty space in front of the camera. */
const CHURN_NEAR = 0.1; // matches the ascii mosaic's rate, so the hands read alike whichever renderer they wear
const CHURN_FAR = 0.015;
function churnForDepth(z: number) {
  const d = Math.min(1, Math.max(0, (-z - 70) / (1040 - 70)));
  return CHURN_NEAR + (CHURN_FAR - CHURN_NEAR) * d;
}

/** Perspective projection factor: element sizes/offsets are authored as what
 * you SEE at p=0; this converts them to the actual (larger, deeper) values. */
function proj(z: number) {
  return (PERSP - z) / PERSP;
}

function layerTransform(l: SceneLayer, z: number) {
  const base = `translate3d(-50%, -50%, ${z.toFixed(1)}px)`;
  if (l.kind === 'floor') return `${base} rotateX(78deg)`;
  return l.rot ? `${base} rotate(${l.rot}deg)` : base;
}

const CONTENT_FADE_END = 0.12; // hero tagline/name/nav are gone by this fraction

export default function Hero() {
  const taglineRef = useRef<HTMLDivElement>(null);
  const scrollWrapRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  const washRef = useRef<HTMLDivElement>(null);
  const sceneRef = useRef<HTMLDivElement>(null);
  const layerRefs = useRef<Array<HTMLDivElement | null>>([]);
  const [tallHero, setTallHero] = useState(true);

  useEffect(() => {
    if (!taglineRef.current) return;
    gsap.fromTo(
      taglineRef.current,
      { opacity: 0, y: 16 },
      { opacity: 1, y: 0, duration: 1, delay: 0.6, ease: 'power3.out' }
    );
  }, []);

  useEffect(() => {
    setTallHero(!window.matchMedia('(prefers-reduced-motion: reduce)').matches);
  }, []);

  // Fit the rail pattern: snap the repeat-tile height so a whole number of
  // triangle cells fills the rail exactly — no clipped cell at the bottom.
  useEffect(() => {
    const wrap = scrollWrapRef.current;
    if (!wrap) return;
    const rail = wrap.querySelector<HTMLElement>('.hero-rail');
    const fit = () => {
      if (!rail) return;
      const h = rail.clientHeight;
      const idealTile = rail.clientWidth * (72 / 40); // 2 square-ish cells per tile
      const n = Math.max(1, Math.round(h / idealTile));
      wrap.style.setProperty('--rail-tile', `${(h / n).toFixed(2)}px`);
    };
    fit();
    window.addEventListener('resize', fit);
    return () => window.removeEventListener('resize', fit);
  }, []);

  // Tracks whether any part of the hero (including mid-flythrough, not just
  // the very top) is on screen, persisted so Layout.astro's preloader-skip
  // script can read it on the NEXT load: refreshing while still within the
  // hero replays the intro (Preloader.tsx resets scroll to top while hidden
  // behind its curtain), but refreshing after scrolling into the regular
  // page content skips it and leaves scroll position alone.
  useEffect(() => {
    const wrap = scrollWrapRef.current;
    if (!wrap) return;
    const io = new IntersectionObserver(
      ([entry]) => {
        try {
          sessionStorage.setItem('hero-in-view', entry.isIntersecting ? '1' : '0');
        } catch {
          // sessionStorage can throw in private-browsing/sandboxed contexts — the
          // preloader just falls back to always showing on reload in that case.
        }
      },
      { threshold: 0 }
    );
    io.observe(wrap);
    return () => io.disconnect();
  }, []);

  /* Star drift. The sky is scattered once, seeded, so SSR and the first
   * client paint agree — but leaving it there makes the field read as a
   * printed backdrop rather than a sky. Every star re-rolls its position each
   * time its twinkle cycle wraps.
   *
   * It rides the CSS animation rather than a rAF loop of its own: the
   * animationiteration event fires at the one instant the star is guaranteed
   * dark (see the keyframes), the cycle lengths are already random per star
   * so no two move together, and an idle sky costs nothing. Positions move,
   * never the depth — a star that changed z would slide through the parallax
   * and give the whole trick away.
   *
   * Math.random, not the seeded sprng: the seed exists to keep hydration
   * stable, and by now hydration is long done. */
  useEffect(() => {
    const scene = sceneRef.current;
    if (!scene) return;
    function onIteration(e: AnimationEvent) {
      const mark = e.target;
      // Lit stars carry a glow element animating on the same cycle; keying off
      // the glyph alone keeps one move per star per cycle rather than two.
      if (!(mark instanceof HTMLElement) || !mark.classList.contains('hl-spark')) return;
      const hl = mark.closest<HTMLElement>('.hl');
      const bandIndex = Number(hl?.dataset.band);
      const projection = Number(hl?.dataset.proj);
      const band = SPARK_BANDS[bandIndex];
      if (!hl || !band || !Number.isFinite(projection)) return;
      const x = band.x0 + Math.random() * band.xs;
      const y = band.y0 + Math.random() * band.ys;
      hl.style.left = `calc(50% + var(--stageW) * ${((x * projection) / 100).toFixed(4)})`;
      hl.style.top = `calc(50% + var(--stageH) * ${((y * projection) / 100).toFixed(4)})`;
    }
    scene.addEventListener('animationiteration', onIteration);
    return () => scene.removeEventListener('animationiteration', onIteration);
  }, []);

  useEffect(() => {
    if (!tallHero) return;
    ensureGsap();
    const wrap = scrollWrapRef.current;
    const content = contentRef.current;
    if (!wrap || !content) return;

    const layers = layerRefs.current.filter((el): el is HTMLDivElement => el !== null);

    const wash = washRef.current;

    /* ---- camera aim ----------------------------------------------------
     * The dolly only changes each layer's z. CSS perspective then scales a
     * layer's offset from the stage centre by P/(P - z), so ANY layer not
     * dead centre swings further off centre the closer it gets — the camera
     * is effectively flying at the middle of the stage, which is empty. The
     * brain sits 11% of the stage above centre, so it climbed out of frame
     * and left the zoom pointed at a patch of floor.
     *
     * Fixing it by moving the brain alone would tear it off the scenery
     * around it. Instead the whole scene pans, which is what a camera
     * actually does when it changes what it is pointed at: the brain holds
     * still and everything else slides past it.
     *
     * Offsets are measured off the element rather than recomputed from
     * --stageW/--stageH, which are min() expressions that do not reliably
     * resolve to px through getComputedStyle. offsetTop is the `top: calc(...)`
     * value before the -50% self-centring translate, so subtracting the
     * stage's half-height gives the layer's own offset directly. */
    const aimIndex = LAYERS.findIndex((l) => l.id === 'brain');
    const aimEl = aimIndex >= 0 ? layers[aimIndex] : undefined;
    const aimLayer = aimIndex >= 0 ? LAYERS[aimIndex] : undefined;
    let aimOffX = 0;
    let aimOffY = 0;
    const measureAim = () => {
      const scene = sceneRef.current;
      if (!aimEl || !scene) return;
      aimOffX = aimEl.offsetLeft - scene.clientWidth / 2;
      aimOffY = aimEl.offsetTop - scene.clientHeight / 2;
    };
    measureAim();

    const update = (p: number) => {
      // exponent > 1 makes the camera accelerate through the scroll — the
      // "pulled into the light" feeling of an opening cinematic
      const pl = Math.max(0, (p - DOLLY_START) / (1 - DOLLY_START));
      const pe = Math.pow(pl, 1.55);
      const dz = pe * TRAVEL;

      const scene = sceneRef.current;
      if (scene && aimLayer) {
        /* Tracks the subject for the WHOLE dolly. Two earlier attempts to
           taper this off were both solving a problem that does not exist
           here: P/(P - z) does run away near the perspective plane, but the
           brain never gets near it — TRAVEL only carries it to z 460 of a
           740 clamp, a bounded 2.35x. Damping by the subject's fade made the
           scale-vs-fade product spike and lurched the scene 106px; freezing
           the aim early was smooth but let the brain drift back off centre
           at the end, which reads as the camera releasing it and panning
           away. Following it all the way is both smooth and steady. */
        const aimZ = Math.min(aimLayer.z + dz, PERSP - 60);
        // Where the subject sits on screen now, and where it sat at rest.
        const now = PERSP / (PERSP - aimZ);
        const rest = PERSP / (PERSP - aimLayer.z);
        // Ease from the authored composition to dead centre across the
        // dolly, so the resting frame is untouched and the zoom ends with
        // the subject centred rather than merely un-drifted.
        const centring = 1 - pe;
        const panX = aimOffX * rest * centring - aimOffX * now;
        const panY = aimOffY * rest * centring - aimOffY * now;
        scene.style.transform = `translate3d(${panX.toFixed(2)}px, ${panY.toFixed(2)}px, 0)`;
      }

      layers.forEach((el, i) => {
        const l = LAYERS[i];
        const zNow = Math.min(l.z + dz, PERSP - 60);
        let op = l.op ?? 1;
        if (zNow > KILL_START) op *= Math.max(0, 1 - (zNow - KILL_START) / KILL_RANGE);
        el.style.transform = layerTransform(l, zNow);
        el.style.opacity = op.toFixed(3);
      });

      const fadeP = Math.min(1, p / CONTENT_FADE_END);
      content.style.opacity = (1 - fadeP).toFixed(3);
      content.style.filter = fadeP > 0 ? `blur(${(fadeP * 6).toFixed(1)}px)` : 'none';

      // Finale: the light swallows the screen over the last stretch, so the
      // sticky release hands the next section a bright frame to rise over.
      if (wash) {
        const wp = Math.min(1, Math.max(0, (p - 0.84) / 0.14));
        const eased = wp * wp * (3 - 2 * wp);
        wash.style.opacity = eased.toFixed(3);
      }
    };

    // Dev-only tuning hook: /?heroP=0.5 freezes the dolly at that progress.
    if (import.meta.env.DEV) {
      const raw = new URLSearchParams(window.location.search).get('heroP');
      const dbg = raw === null ? NaN : Number(raw);
      if (!Number.isNaN(dbg) && dbg >= 0) {
        update(Math.min(1, dbg));
        return;
      }
    }

    const trigger = ScrollTrigger.create({
      trigger: wrap,
      start: 'top top',
      end: 'bottom bottom',
      scrub: true,
      onUpdate: (self) => update(self.progress),
    });

    // Prop-setup entrance: on a fresh intro (not a skip-reload), the scene
    // assembles like stagehands placing a set — frame and light first, then
    // scenery lowered in, actors dropped onto the boards with a small
    // overshoot, hands reaching in last. `immediateRender: true` parks every
    // prop in its hidden "from" state at hydration, while the preloader
    // curtain still covers the stage; the timeline starts as the curtain
    // lifts. Animates .hl-prop wrappers only — the dolly owns .hl.
    let entrance: gsap.core.Timeline | undefined;
    const freshIntro = document.documentElement.getAttribute('data-intro') !== 'skip';
    if (freshIntro && sceneRef.current) {
      const q = gsap.utils.selector(wrap);
      const prop = (id: string) => q(`[data-prop="${id}"]`);
      const ir = { immediateRender: true } as const;
      entrance = gsap.timeline({ delay: 2.3, defaults: { ease: 'power3.out' } });
      entrance
        .from(q('.hero-rail'), { opacity: 0, duration: 0.7, ...ir }, 0)
        .from(prop('interior'), { opacity: 0, duration: 1.0, ...ir }, 0.1)
        .from(prop('floor'), { opacity: 0, yPercent: 18, duration: 0.9, ...ir }, 0.35)
        .from(prop('clouds'), { yPercent: -180, duration: 1.0, ...ir }, 0.5)
        .from(prop('halo'), { opacity: 0, duration: 1.0, ...ir }, 0.8)
        .from(prop('brain'), { yPercent: 55, opacity: 0, duration: 1.0, ease: 'power2.out', ...ir }, 0.8)
        .from(prop('devil'), { yPercent: -140, opacity: 0, duration: 0.75, ease: 'back.out(1.3)', ...ir }, 1.15)
        .from(prop('cockatrice'), { yPercent: -140, opacity: 0, duration: 0.75, ease: 'back.out(1.3)', ...ir }, 1.35)
        .from(prop('hand-left'), { xPercent: -75, opacity: 0, duration: 0.9, ...ir }, 1.55)
        .from(prop('hand-right'), { xPercent: 75, opacity: 0, duration: 0.9, ...ir }, 1.7)
        .from(q('[data-spark]'), { opacity: 0, scale: 0.5, duration: 0.7, stagger: 0.045, ...ir }, 0.75);
    }

    // Head-tracking parallax: easing the perspective-origin toward the
    // pointer shifts every layer proportionally to its depth — the cheap,
    // honest way to make the box read as a real space you're peering into.
    const scene = sceneRef.current;
    const look = { x: 0, y: 0 };
    const lookTarget = { x: 0, y: 0 };
    const canHover = window.matchMedia('(hover: hover)').matches;
    const onPointerMove = (e: PointerEvent) => {
      lookTarget.x = (e.clientX / window.innerWidth - 0.5) * 7;
      lookTarget.y = (e.clientY / window.innerHeight - 0.5) * 5;
    };
    const lookTick = () => {
      look.x += (lookTarget.x - look.x) * 0.05;
      look.y += (lookTarget.y - look.y) * 0.05;
      if (scene) scene.style.perspectiveOrigin = `${(50 + look.x).toFixed(3)}% ${(50 + look.y).toFixed(3)}%`;
    };
    if (canHover && scene) {
      window.addEventListener('pointermove', onPointerMove);
      gsap.ticker.add(lookTick);
    }

    // The aim offsets are measured in px, so they go stale on resize.
    window.addEventListener('resize', measureAim);

    return () => {
      trigger.kill();
      entrance?.kill();
      window.removeEventListener('resize', measureAim);
      if (sceneRef.current) sceneRef.current.style.transform = '';
      if (canHover && scene) {
        window.removeEventListener('pointermove', onPointerMove);
        gsap.ticker.remove(lookTick);
      }
    };
  }, [tallHero]);

  return (
    <div ref={scrollWrapRef} className={`hero-scroll-wrap${tallHero ? '' : ' is-compact'}`}>
      <section className="hero">
        <div className="hero-canvas" aria-hidden="true">
          <div ref={sceneRef} className="hero-scene">
            {LAYERS.map((l, i) => {
              const f = proj(l.z);
              return (
                <div
                  key={l.id}
                  ref={(el) => {
                    layerRefs.current[i] = el;
                  }}
                  className="hl"
                  style={{
                    width: `calc(var(--stageW) * ${((l.w * f) / 100).toFixed(4)})`,
                    aspectRatio: `${l.ar}`,
                    left: `calc(50% + var(--stageW) * ${(((l.x ?? 0) * f) / 100).toFixed(4)})`,
                    top: `calc(50% + var(--stageH) * ${(((l.y ?? 0) * f) / 100).toFixed(4)})`,
                    transform: layerTransform(l, l.z),
                    opacity: l.op ?? 1,
                  }}
                  /* Both read back by the drift effect, which rewrites
                     left/top and needs this layer's own projection factor to
                     convert a stage-space position into one. */
                  data-band={l.kind === 'spark' ? l.band : undefined}
                  data-proj={l.kind === 'spark' ? f.toFixed(4) : undefined}
                >
                  <div
                    className="hl-prop"
                    data-prop={l.id}
                    data-spark={l.kind === 'spark' ? '' : undefined}
                    data-flick={l.kind === 'spark' ? l.flick : undefined}
                  >
                    {l.kind === 'spark' && (
                      <>
                        {/* A lit particle is the same MARK as a dark one, sat
                            on a bloom its own size — not a soft blob. The
                            glyph has to stay legible or the sky goes back to
                            being lens flares. Both children share one
                            duration/delay so the bloom blinks with its mark
                            rather than beating against it. */}
                        {l.spark === 'light' && (
                          <div
                            className="hl-light"
                            style={{
                              animationDuration: `${l.dur}s`,
                              animationDelay: `${l.delay}s`,
                              ...({ '--lightc': l.lightc } as CSSProperties),
                            }}
                          />
                        )}
                        <div
                          className="hl-ink hl-spark"
                          style={{
                            backgroundColor: l.spark === 'light' ? l.lightc : l.tone,
                            WebkitMaskImage: l.mask,
                            maskImage: l.mask,
                            animationDuration: `${l.dur}s`,
                            animationDelay: `${l.delay}s`,
                          }}
                        />
                      </>
                    )}
                    {l.kind === 'interior' && (
                      <div className="hl-interior">
                        <div className="hl-glow" />
                      </div>
                    )}
                    {l.kind === 'halo' && <div className="hl-halo" />}
                    {l.kind === 'floor' && <div className="hl-floor" />}
                    {l.ascii && (
                      <div className={`hl-art${l.idle ? ` idle-${l.idle}` : ''}`}>
                        <HeroAsciiArt src={l.ascii} srcLight={l.asciiLight} seed={i + 1} variant={l.render ?? 'ascii'} ink={l.ink} churn={churnForDepth(l.z)} />
                      </div>
                    )}
                    {l.mask && l.kind !== 'spark' && (
                      <div className={`hl-art${l.idle ? ` idle-${l.idle}` : ''}`}>
                        <div
                          className={`hl-ink${l.maskLight ? ' theme-dark-only' : ''}`}
                          style={{ backgroundColor: l.tone, WebkitMaskImage: l.mask, maskImage: l.mask }}
                        />
                        {l.maskLight && (
                          <div
                            className="hl-ink theme-light-only"
                            style={{ backgroundColor: l.toneLight, WebkitMaskImage: l.maskLight, maskImage: l.maskLight }}
                          />
                        )}
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          {/* The screen IS the proscenium: dogtooth rails pinned to the
              viewport edges, outside the dolly — they never fly past. */}
          <div className="hero-rail is-left" />
          <div className="hero-rail is-right" />
        </div>

        <div ref={washRef} className="hero-wash" aria-hidden="true" />

        <div ref={contentRef} className="hero-content">
          <div ref={taglineRef} className="hero-tagline">
            Quiet creator, <span className="other-accent">bringing ideas to life</span>,
            <br />
            through motion, detail and softness.
          </div>

          <div className="hero-bottom">
            <h1 className="hero-name">Blaz Pocrnja.</h1>
            <div className="hero-bar">
              <div className="hero-bar-left">
                <HoverLink label="v1.0" />
              </div>
              <nav className="hero-bar-center" aria-label="Social links">
                {SOCIALS.map((s, i) => (
                  <span key={s.label} style={{ display: 'flex', gap: '0.5em' }}>
                    <a href={s.href} target="_blank" rel="noopener noreferrer">
                      <HoverLink label={s.label} />
                    </a>
                    {i < SOCIALS.length - 1 && <span className="sep">/</span>}
                  </span>
                ))}
              </nav>
              <nav className="hero-bar-right" aria-label="Main navigation">
                {NAV.map((n) => (
                  <a key={n.label} href={n.href}>
                    <HoverLink label={n.label} />
                  </a>
                ))}
              </nav>
            </div>
          </div>
        </div>
      </section>

      {/* dangerouslySetInnerHTML avoids a React SSR/hydration text-escaping mismatch for raw-text elements like <style> (this one trips it via the `>` in `.hero-content > *`) */}
      <style dangerouslySetInnerHTML={{ __html: `
        .hero-scroll-wrap {
          position: relative;
          height: 400vh;
        }
        .hero-scroll-wrap.is-compact {
          height: 100vh;
        }
        .hero {
          position: sticky;
          top: 0;
          height: 100vh;
          min-height: 560px;
          overflow: hidden;
        }
        .hero-scroll-wrap.is-compact .hero {
          position: relative;
        }
        .hero-canvas {
          position: absolute;
          inset: 0;
          z-index: 0;
          background: var(--bg);
        }
        .hero-scene {
          position: absolute;
          inset: 0;
          perspective: ${PERSP}px;
          --stageW: min(94vw, 140vh);
          --stageH: calc(var(--stageW) / 1.6);
        }
        @media (max-width: 640px) {
          .hero-scene {
            --stageW: min(96vw, 120vh);
          }
        }
        .hl {
          position: absolute;
          will-change: transform, opacity;
          pointer-events: none;
        }
        /* Three transform tiers that never fight: .hl belongs to the scroll
           dolly (JS), .hl-prop to the one-shot prop-setup entrance (GSAP),
           .hl-art to the CSS idle loops. */
        .hl-prop {
          position: absolute;
          inset: 0;
        }
        .hl-art,
        .hl-ink,
        .hl-light,
        .hl-interior,
        .hl-halo,
        .hl-floor,
        .hl-frame {
          position: absolute;
          inset: 0;
        }
        .hl-ink {
          -webkit-mask-size: 100% 100%;
          mask-size: 100% 100%;
          -webkit-mask-repeat: no-repeat;
          mask-repeat: no-repeat;
        }
        .theme-light-only {
          display: none;
        }
        :root[data-theme='light'] .theme-light-only {
          display: block;
        }
        :root[data-theme='light'] .theme-dark-only {
          display: none;
        }
        /* Digital twinkle. A star is either lit or it is not: steps(1, end)
           holds each keyframe's value until the next one lands, so every
           change is a hard cut. The old loop ramped opacity AND scaled the
           mark, which is a PULSE — it breathes, and breathing is the organic
           register this sky is trying to leave. Nothing here touches
           transform, so nothing swells.

           Three rhythms rather than one: with a single pattern, 64 particles
           on staggered delays still visibly share a beat. Duration and phase
           come from each particle's own inline style. */
        .hl-spark,
        .hl-light {
          animation: hl-twinkle-a 3s steps(1, end) infinite;
        }
        [data-flick='1'] .hl-spark,
        [data-flick='1'] .hl-light {
          animation-name: hl-twinkle-b;
        }
        [data-flick='2'] .hl-spark,
        [data-flick='2'] .hl-light {
          animation-name: hl-twinkle-c;
        }
        /* The bloom UNDER a lit particle — it is no longer the particle
           itself. Deliberately tight (gone by 62% of the box) and with no
           hot core: it sits behind a crisp glyph, and the old wide falloff
           swallowed that glyph whole and turned the mark back into a soft
           blob. Composited additively so overlaps still bloom like real
           lights. The color family comes from --lightc per particle. */
        .hl-light {
          --lightc: var(--accent);
          background: radial-gradient(circle,
            color-mix(in srgb, var(--lightc) 45%, transparent) 0%,
            color-mix(in srgb, var(--lightc) 22%, transparent) 34%,
            transparent 62%);
          mix-blend-mode: screen;
        }
        :root[data-theme='light'] .hl-light {
          mix-blend-mode: multiply;
        }
        /* Each rhythm now opens and closes on BLACK. That dark head is what
           lets a star move: the drift effect repositions on animationiteration,
           which fires exactly at the wrap, and with steps(1, end) the 0%
           keyframe holds until the next one — so the star is invisible for the
           first few percent of its cycle and lands somewhere new without ever
           being seen to travel. Take the dark head away and stars teleport
           across the sky in full view. */
        @keyframes hl-twinkle-a {
          0% { opacity: 0; }
          5% { opacity: 1; }
          27% { opacity: 0.14; }
          36% { opacity: 0.9; }
          55% { opacity: 0.36; }
          64% { opacity: 1; }
          88% { opacity: 0.2; }
          95% { opacity: 0; }
        }
        @keyframes hl-twinkle-b {
          0% { opacity: 0; }
          6% { opacity: 0.5; }
          18% { opacity: 1; }
          31% { opacity: 0.1; }
          48% { opacity: 0.82; }
          60% { opacity: 0.26; }
          79% { opacity: 1; }
          93% { opacity: 0; }
        }
        @keyframes hl-twinkle-c {
          0% { opacity: 0; }
          4% { opacity: 0.86; }
          20% { opacity: 0.3; }
          40% { opacity: 1; }
          53% { opacity: 0.6; }
          70% { opacity: 0.12; }
          85% { opacity: 0.96; }
          96% { opacity: 0; }
        }
        /* The light source behind the scenery — glow only, no panel fill:
           a visible rectangle edge against the void reads as a seam. */
        .hl-interior {
          background: transparent;
        }
        .hl-glow {
          position: absolute;
          inset: 0;
          border-radius: inherit;
          background: radial-gradient(ellipse 62% 58% at 50% 40%, color-mix(in srgb, var(--accent) 34%, transparent), transparent 72%);
          animation: hl-flicker 5.2s ease-in-out infinite;
        }
        .hl-halo {
          background: radial-gradient(circle, color-mix(in srgb, var(--accent) 42%, transparent), transparent 68%);
          animation: hl-flicker 4.1s ease-in-out -1.7s infinite;
        }
        .hl-floor {
          /* both checker cells are OPAQUE (resolved against --bg, not
             transparent) — either half being see-through let the mountains
             bleed through every other tile. The floor's own mask below still
             fades the whole plane to nothing at its far edges, which is the
             only place scenery should show through. */
          background: repeating-conic-gradient(color-mix(in srgb, var(--fg) 30%, var(--bg)) 0% 25%, var(--bg) 0% 50%);
          background-size: clamp(64px, 8.5vw, 118px) clamp(64px, 8.5vw, 118px);
          -webkit-mask-image: radial-gradient(closest-side, #000 45%, transparent 92%);
          mask-image: radial-gradient(closest-side, #000 45%, transparent 92%);
        }
        /* Screen-edge proscenium rails: full viewport height, alternating
           right triangles like the laser-cut border of the physical box.
           The strip itself is SOLID (page-colored) — the scene never shows
           through it; the triangles paint on top via the mask. */
        .hero-rail {
          position: absolute;
          top: 0;
          bottom: 0;
          width: clamp(44px, 5.2vw, 92px);
          background: var(--bg);
          /* the strip's rule — flips to the correct side on the mirrored
             right rail along with the rest of the element */
          border-right: 2px solid color-mix(in srgb, var(--fg) 40%, var(--bg));
        }
        .hero-rail::before {
          content: '';
          position: absolute;
          inset: 0;
          background: color-mix(in srgb, var(--fg) 40%, var(--bg));
          -webkit-mask-image: ${RAIL};
          mask-image: ${RAIL};
          -webkit-mask-size: 100% var(--rail-tile, auto);
          mask-size: 100% var(--rail-tile, auto);
          -webkit-mask-repeat: repeat-y;
          mask-repeat: repeat-y;
        }
        .hero-rail.is-left {
          left: 0;
        }
        .hero-rail.is-right {
          right: 0;
          transform: scaleX(-1);
        }
        /* Idle life: candle-flicker on the light, game-style idle loops on
           the cast. These animate INNER elements only — the outer .hl
           transforms belong to the scroll dolly, so the two never fight. */
        @keyframes hl-flicker {
          0%, 100% { opacity: 1; }
          31% { opacity: 0.82; }
          47% { opacity: 0.95; }
          62% { opacity: 0.78; }
          81% { opacity: 0.92; }
        }
        /* everything hangs weightless: the same gentle bob at staggered
           periods — puppets suspended in the box */
        @keyframes hl-idle-float {
          from { transform: translateY(1.4%) rotate(-0.7deg); }
          to { transform: translateY(-2%) rotate(0.6deg); }
        }
        /* will-change on the animated elements themselves (not just their
           .hl ancestor) promotes each to its own compositor layer, so this
           continuous sway transforms an already-rasterized bitmap on the
           GPU instead of repainting on every frame — cheap for a masked
           image, but load-bearing now that brain/hands are thousands of
           text glyphs: without it, an unpromoted layer repaints that whole
           subtree's content every frame just to move it, all day. */
        .idle-float,
        .idle-float-b,
        .idle-float-c,
        .idle-hands {
          will-change: transform;
        }
        .idle-float { animation: hl-idle-float 5.6s ease-in-out infinite alternate; }
        .idle-float-b { animation: hl-idle-float 6.8s ease-in-out -2.4s infinite alternate; }
        .idle-float-c { animation: hl-idle-float 7.6s ease-in-out -4.6s infinite alternate; }
        /* the hands share ONE plane and ONE rhythm — first-person-camera
           hands, swaying together, so identical timing and no phase offset */
        @keyframes hl-idle-hands {
          from { transform: translate(0.5%, 1%) rotate(0.25deg); }
          to { transform: translate(-0.5%, -1.4%) rotate(-0.25deg); }
        }
        .idle-hands { animation: hl-idle-hands 5s ease-in-out infinite alternate; }
        /* Finale wash: dark theme fades to black with a dying ember at the
           center (a white flash out of the void was jarring); light theme
           blooms to white — the literal lamp, not a surface token. */
        .hero-wash {
          position: absolute;
          inset: 0;
          z-index: 2;
          pointer-events: none;
          opacity: 0;
          background: radial-gradient(circle at 50% 44%,
            color-mix(in srgb, var(--accent) 22%, #000),
            color-mix(in srgb, var(--accent) 8%, #000) 50%,
            #000 100%);
          will-change: opacity;
        }
        :root[data-theme='light'] .hero-wash {
          background: radial-gradient(circle at 50% 44%,
            color-mix(in srgb, var(--accent) 42%, #fff),
            color-mix(in srgb, var(--accent) 18%, #fff) 55%,
            #fff 100%);
        }
        .hero-content {
          position: absolute;
          inset: 0;
          z-index: 1;
          pointer-events: none;
          will-change: opacity, filter;
        }
        /* Only the actual interactive bits re-enable pointer-events, not
           whole containers like .hero-bottom — that div's empty space is
           still a hit-testable box otherwise, and at z-index 1 it sits above
           the canvas, shadowing hover on anything beneath it (the ascii
           layers, once they became hoverable). Same fix as .footer-content. */
        .hero-content a,
        .hero-content .chr-hover {
          pointer-events: auto;
        }
        .hero-tagline {
          position: absolute;
          top: var(--container-pad);
          left: var(--container-pad);
          font-family: var(--font-serif);
          font-size: clamp(1.6rem, 3.2vw, 2.6rem);
          font-weight: 400;
          line-height: 1.3;
          max-width: 14ch;
        }
        .hero-bottom {
          position: absolute;
          left: var(--container-pad);
          right: var(--container-pad);
          bottom: var(--container-pad);
        }
        .hero-name {
          font-family: var(--font-display);
          font-size: clamp(2.5rem, 9vw, 6.5rem);
          font-weight: 900;
          letter-spacing: 0;
          line-height: 0.9;
          /* The trailing 1rem + 1px is what the removed .hero-line divider used
             to occupy (its own height plus its margin). Folded into the name's
             margin rather than added back as margin-top on .hero-bar, because
             adjacent siblings collapse in this block container — a 1rem
             margin-top simply vanished inside this larger one, and the bar
             crept 17px closer. Kept so deleting the rule changed nothing but
             the rule itself. */
          margin-bottom: calc(clamp(1.5rem, 4vw, 3rem) + 1rem + 1px);
        }
        /* Three columns rather than space-between. space-between only centres
           its middle child when the OUTER two are the same width, and here
           they are nowhere near it — "v1.0" is 46px against 174px of nav — so
           the social links sat exactly (174 - 46) / 2 = 64px left of centre.
           Equal 1fr tracks either side centre the middle column no matter
           what flanks it. minmax(0, 1fr) rather than plain 1fr so the outer
           tracks may shrink below their content on a narrow viewport instead
           of forcing the bar to overflow. */
        .hero-bar {
          display: grid;
          grid-template-columns: minmax(0, 1fr) auto minmax(0, 1fr);
          align-items: center;
          font-family: var(--font-mono);
          font-size: 0.8rem;
          text-transform: uppercase;
          letter-spacing: 0.03em;
          gap: 0.75rem;
        }
        .hero-bar-left {
          justify-self: start;
        }
        .hero-bar-center {
          justify-self: center;
        }
        .hero-bar-right {
          justify-self: end;
        }
        /* the near-camera hands pass right behind these labels — each group
           carries a translucent page-colored chip so the type stays legible
           over the dither without walling off the scene */
        .hero-bar-left,
        .hero-bar-center,
        .hero-bar-right {
          background: color-mix(in srgb, var(--bg) 72%, transparent);
          padding: 0.3em 0.55em;
          margin: -0.3em -0.55em;
          border-radius: 4px;
        }
        .hero-bar-center {
          display: flex;
          gap: 0.5em;
        }
        .hero-bar-right {
          display: flex;
          gap: 1.5em;
        }
        .sep {
          color: var(--fg-dim);
        }
        @media (max-width: 640px) {
          .hero-tagline {
            max-width: calc(100% - 2 * var(--container-pad) - 5.5rem);
          }
        }
        @media (prefers-reduced-motion: reduce) {
          .hl-glow,
          .hl-halo,
          .hl-spark,
          .hl-light,
          .idle-float,
          .idle-float-b,
          .idle-float-c,
          .idle-hands {
            animation: none;
          }
        }
      ` }} />
    </div>
  );
}
